### ISSUE TITLE
IndexIgnore problem

### ISSUE THREAD

**Issue by dusnake** [yaroslaff/a2conf#2]
Good morning.

Using your module (thanks in advance), I have seen that when parsing the httpd.conf file, it has generated this problem:

unmodified httpd.conf file:

IndexIgnore .??* *~ *# HEADER* README* RCS CVS *,v *,t

file after passing a2conf:

IndexIgnore .??* *~ * # HEADER* README* RCS CVS *,v *,t

The following parameter: *# adds a space leaving it as * #

and causes problems in my application. I don't know if any correction can be made so that it doesn't put that space in directives like this one.

Thanks a lot!!

**Comment by yaroslaff** [comment]
Could you please write exact instruction how to reproduce it? (I see many differences between two IndexIgnore statements, e.g. first one has 2 asterisk before # and 3 after #, second one as 3 asterisk before # and 4 after.  (not matching to what you write in words)

Maybe you can attach small conf file and exact commands to produce problem?

**Comment by yaroslaff** [comment]
Try to upgrade a2conf to 0.3.2 
`pip3 install -U a2conf
`
New version tries to keep same number of space-characters as in original string

**Comment by dusnake** [comment]
I launch it through ansible using python 3:

ansible.builtin.script: files/rules/temporal.py "httpd.conf"
      args:
        executable: python3
        
original directive:
    `IndexIgnore .??* *~ *# HEADER* README* RCS CVS *,v *,t`

directive after writing the file:
    `IndexIgnore .??* *~ * # HEADER* README* RCS CVS *,v *,t`

only doing this: 

`#!/usr/bin/env python3
import sys
import a2conf
import json
import re

root = a2conf.Node(sys.argv[1])
fichero = (sys.argv[1])

root.write_file(fichero)`



a piece of code as an example:

  AddIcon /icons/folder.gif ^^DIRECTORY^^ 
  AddIcon /icons/blank.gif ^^BLANKICON^^ 
  DefaultIcon /icons/unknown.gif 
  IndexIgnore .??* *~ * # HEADER* README* RCS CVS *,v *,t
  AddEncoding x-compress Z 
  AddEncoding x-gzip gz tgz 
  AddType application/x-tar .tgz 
  AddType image/x-icon .ico

**Comment by yaroslaff** [comment]
Seems we were writing comments at same time. Please check if new version of a2conf has this problem solved?

**Comment by dusnake** [comment]
works perfect mate, thanks  a lot!!
